"""add_refresh_token_table

Revision ID: 460d2c67b829
Revises: g2a3b4c5d678
Create Date: 2026-03-29 18:15:24.569571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '460d2c67b829'
down_revision: Union[str, Sequence[str], None] = 'g2a3b4c5d678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refreshtoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refreshtoken', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refreshtoken_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refreshtoken_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refreshtoken', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refreshtoken_user_id'))
        batch_op.drop_index(batch_op.f('ix_refreshtoken_token_hash'))

    op.drop_table('refreshtoken')
    # ### end Alembic commands ###
